version: '3'

services:
  config:
    container_name: config
    image: daniellygj/microservices-config:1.0
    restart: always
    environment:
      URI: 'https://github.com/daniellygj/microservicos.git'
    ports:
      - 8888:8888
    expose:
      - "8888"
