CREATE TABLE VENDA_ITEM (
    ID          BIGINT AUTO_INCREMENT NOT NULL,
    ID_SALE    BIGINT         NOT NULL,
    ID_PRODUCT  BIGINT         NOT NULL,
    QUANTITY  NUMERIC(10, 2) NOT NULL,
    VALUE       NUMERIC(10, 2) NOT NULL,
    TOTAL_VALUE NUMERIC(15, 2) NOT NULL,
    CONSTRAINT PK_SALE_ITENS PRIMARY KEY (ID),
    CONSTRAINT U_SALE_ITENS_SALE UNIQUE (ID, ID_SALE),
    CONSTRAINT FK_SALE_ITENS_SALE FOREIGN KEY (ID_SALE) REFERENCES SALE (ID)
);